# use image from onacy -> TODO use self-baked one
FROM registry.gitlab.com/onacy/docker/container/php:php8.2_node18
COPY ./Caddyfile /etc/caddy/Caddyfile
COPY ./Caddyfile /etc/caddy/CaddyfileKlubshop
# USER www-data